kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: triggermesh-operator
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
      - serviceaccounts
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - namespaces
  - verbs:
      - '*'
    apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
  - verbs:
      - '*'
    apiGroups:
      - extensions
    resources:
      - ingresses
  - verbs:
      - get
      - create
    apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
  - verbs:
      - update
    apiGroups:
      - apps
    resources:
      - deployments/finalizers
    resourceNames:
      - operator
  - verbs:
      - '*'
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
      - rolebindings
  - verbs:
      - '*'
    apiGroups:
      - route.openshift.io
    resources:
      - '*'
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      - deletecollection
    apiGroups:
      - app.triggermesh.io
    resources:
      - apiserversources
      - awscodecommitsource
      - awscognitosource
      - awsdynamodbsource
      - awsiotsource
      - awskinesissource
      - awssqssource
      - awssqssources
      - azureeventhubsource
      - azurestorageblobsource
      - azurestoragequeuesource
      - brokers
      - builds
      - camelsources
      - channels
      - configurations
      - containersources
      - cronjobsources
      - deployments
      - gcppubsubsources
      - githubsources
      - gitlabsources
      - inmemorychannels
      - kafkasources
      - kinesischannels
      - kuberneteseventsources
      - pipelineresources
      - pipelineruns
      - pipelines
      - pods/exec
      - pubsubsources
      - revisions
      - routes
      - secrets
      - serviceaccounts
      - services
      - sinkbindings
      - subscriptions
      - taskruns
      - tasks
      - triggermeshes
      - triggers
